package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"
	"errors"

	"github.com/hawa130/computility-cloud/ent/user"
	"github.com/hawa130/computility-cloud/graph/model"
	"github.com/hawa130/computility-cloud/internal/auth"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	record, err := r.client.User.Query().Where(user.PhoneEQ(input.Phone)).Only(ctx)
	if err != nil {
		return nil, err
	}
	result, err := auth.ComparePasswordAndHash(input.Password, record.Password)
	if err != nil {
		return nil, err
	}
	if !result {
		return nil, errors.New("invalid password")
	}

	token, err := auth.GenerateToken(record.ID)
	if err != nil {
		return nil, err
	}

	return &model.LoginPayload{
		Token: &token,
		User:  record,
	}, nil
}
