// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hawa130/serverx/ent/predicate"
	"github.com/hawa130/serverx/ent/publickey"
	"github.com/hawa130/serverx/ent/user"
	"github.com/rs/xid"
)

// PublicKeyQuery is the builder for querying PublicKey entities.
type PublicKeyQuery struct {
	config
	ctx        *QueryContext
	order      []publickey.OrderOption
	inters     []Interceptor
	predicates []predicate.PublicKey
	withUser   *UserQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*PublicKey) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PublicKeyQuery builder.
func (pkq *PublicKeyQuery) Where(ps ...predicate.PublicKey) *PublicKeyQuery {
	pkq.predicates = append(pkq.predicates, ps...)
	return pkq
}

// Limit the number of records to be returned by this query.
func (pkq *PublicKeyQuery) Limit(limit int) *PublicKeyQuery {
	pkq.ctx.Limit = &limit
	return pkq
}

// Offset to start from.
func (pkq *PublicKeyQuery) Offset(offset int) *PublicKeyQuery {
	pkq.ctx.Offset = &offset
	return pkq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pkq *PublicKeyQuery) Unique(unique bool) *PublicKeyQuery {
	pkq.ctx.Unique = &unique
	return pkq
}

// Order specifies how the records should be ordered.
func (pkq *PublicKeyQuery) Order(o ...publickey.OrderOption) *PublicKeyQuery {
	pkq.order = append(pkq.order, o...)
	return pkq
}

// QueryUser chains the current query on the "user" edge.
func (pkq *PublicKeyQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: pkq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pkq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pkq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(publickey.Table, publickey.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, publickey.UserTable, publickey.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(pkq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PublicKey entity from the query.
// Returns a *NotFoundError when no PublicKey was found.
func (pkq *PublicKeyQuery) First(ctx context.Context) (*PublicKey, error) {
	nodes, err := pkq.Limit(1).All(setContextOp(ctx, pkq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{publickey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pkq *PublicKeyQuery) FirstX(ctx context.Context) *PublicKey {
	node, err := pkq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PublicKey ID from the query.
// Returns a *NotFoundError when no PublicKey ID was found.
func (pkq *PublicKeyQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = pkq.Limit(1).IDs(setContextOp(ctx, pkq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{publickey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pkq *PublicKeyQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := pkq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PublicKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PublicKey entity is found.
// Returns a *NotFoundError when no PublicKey entities are found.
func (pkq *PublicKeyQuery) Only(ctx context.Context) (*PublicKey, error) {
	nodes, err := pkq.Limit(2).All(setContextOp(ctx, pkq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{publickey.Label}
	default:
		return nil, &NotSingularError{publickey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pkq *PublicKeyQuery) OnlyX(ctx context.Context) *PublicKey {
	node, err := pkq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PublicKey ID in the query.
// Returns a *NotSingularError when more than one PublicKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (pkq *PublicKeyQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = pkq.Limit(2).IDs(setContextOp(ctx, pkq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{publickey.Label}
	default:
		err = &NotSingularError{publickey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pkq *PublicKeyQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := pkq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PublicKeys.
func (pkq *PublicKeyQuery) All(ctx context.Context) ([]*PublicKey, error) {
	ctx = setContextOp(ctx, pkq.ctx, ent.OpQueryAll)
	if err := pkq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PublicKey, *PublicKeyQuery]()
	return withInterceptors[[]*PublicKey](ctx, pkq, qr, pkq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pkq *PublicKeyQuery) AllX(ctx context.Context) []*PublicKey {
	nodes, err := pkq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PublicKey IDs.
func (pkq *PublicKeyQuery) IDs(ctx context.Context) (ids []xid.ID, err error) {
	if pkq.ctx.Unique == nil && pkq.path != nil {
		pkq.Unique(true)
	}
	ctx = setContextOp(ctx, pkq.ctx, ent.OpQueryIDs)
	if err = pkq.Select(publickey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pkq *PublicKeyQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := pkq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pkq *PublicKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pkq.ctx, ent.OpQueryCount)
	if err := pkq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pkq, querierCount[*PublicKeyQuery](), pkq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pkq *PublicKeyQuery) CountX(ctx context.Context) int {
	count, err := pkq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pkq *PublicKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pkq.ctx, ent.OpQueryExist)
	switch _, err := pkq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pkq *PublicKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := pkq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PublicKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pkq *PublicKeyQuery) Clone() *PublicKeyQuery {
	if pkq == nil {
		return nil
	}
	return &PublicKeyQuery{
		config:     pkq.config,
		ctx:        pkq.ctx.Clone(),
		order:      append([]publickey.OrderOption{}, pkq.order...),
		inters:     append([]Interceptor{}, pkq.inters...),
		predicates: append([]predicate.PublicKey{}, pkq.predicates...),
		withUser:   pkq.withUser.Clone(),
		// clone intermediate query.
		sql:  pkq.sql.Clone(),
		path: pkq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (pkq *PublicKeyQuery) WithUser(opts ...func(*UserQuery)) *PublicKeyQuery {
	query := (&UserClient{config: pkq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pkq.withUser = query
	return pkq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PublicKey.Query().
//		GroupBy(publickey.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pkq *PublicKeyQuery) GroupBy(field string, fields ...string) *PublicKeyGroupBy {
	pkq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PublicKeyGroupBy{build: pkq}
	grbuild.flds = &pkq.ctx.Fields
	grbuild.label = publickey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.PublicKey.Query().
//		Select(publickey.FieldCreatedAt).
//		Scan(ctx, &v)
func (pkq *PublicKeyQuery) Select(fields ...string) *PublicKeySelect {
	pkq.ctx.Fields = append(pkq.ctx.Fields, fields...)
	sbuild := &PublicKeySelect{PublicKeyQuery: pkq}
	sbuild.label = publickey.Label
	sbuild.flds, sbuild.scan = &pkq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PublicKeySelect configured with the given aggregations.
func (pkq *PublicKeyQuery) Aggregate(fns ...AggregateFunc) *PublicKeySelect {
	return pkq.Select().Aggregate(fns...)
}

func (pkq *PublicKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pkq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pkq); err != nil {
				return err
			}
		}
	}
	for _, f := range pkq.ctx.Fields {
		if !publickey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pkq.path != nil {
		prev, err := pkq.path(ctx)
		if err != nil {
			return err
		}
		pkq.sql = prev
	}
	if publickey.Policy == nil {
		return errors.New("ent: uninitialized publickey.Policy (forgotten import ent/runtime?)")
	}
	if err := publickey.Policy.EvalQuery(ctx, pkq); err != nil {
		return err
	}
	return nil
}

func (pkq *PublicKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PublicKey, error) {
	var (
		nodes       = []*PublicKey{}
		withFKs     = pkq.withFKs
		_spec       = pkq.querySpec()
		loadedTypes = [1]bool{
			pkq.withUser != nil,
		}
	)
	if pkq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, publickey.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PublicKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PublicKey{config: pkq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(pkq.modifiers) > 0 {
		_spec.Modifiers = pkq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pkq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pkq.withUser; query != nil {
		if err := pkq.loadUser(ctx, query, nodes, nil,
			func(n *PublicKey, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	for i := range pkq.loadTotal {
		if err := pkq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pkq *PublicKeyQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*PublicKey, init func(*PublicKey), assign func(*PublicKey, *User)) error {
	ids := make([]xid.ID, 0, len(nodes))
	nodeids := make(map[xid.ID][]*PublicKey)
	for i := range nodes {
		if nodes[i].public_key_user == nil {
			continue
		}
		fk := *nodes[i].public_key_user
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "public_key_user" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pkq *PublicKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pkq.querySpec()
	if len(pkq.modifiers) > 0 {
		_spec.Modifiers = pkq.modifiers
	}
	_spec.Node.Columns = pkq.ctx.Fields
	if len(pkq.ctx.Fields) > 0 {
		_spec.Unique = pkq.ctx.Unique != nil && *pkq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pkq.driver, _spec)
}

func (pkq *PublicKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(publickey.Table, publickey.Columns, sqlgraph.NewFieldSpec(publickey.FieldID, field.TypeString))
	_spec.From = pkq.sql
	if unique := pkq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pkq.path != nil {
		_spec.Unique = true
	}
	if fields := pkq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publickey.FieldID)
		for i := range fields {
			if fields[i] != publickey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pkq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pkq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pkq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pkq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pkq *PublicKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pkq.driver.Dialect())
	t1 := builder.Table(publickey.Table)
	columns := pkq.ctx.Fields
	if len(columns) == 0 {
		columns = publickey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pkq.sql != nil {
		selector = pkq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pkq.ctx.Unique != nil && *pkq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pkq.predicates {
		p(selector)
	}
	for _, p := range pkq.order {
		p(selector)
	}
	if offset := pkq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pkq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PublicKeyGroupBy is the group-by builder for PublicKey entities.
type PublicKeyGroupBy struct {
	selector
	build *PublicKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pkgb *PublicKeyGroupBy) Aggregate(fns ...AggregateFunc) *PublicKeyGroupBy {
	pkgb.fns = append(pkgb.fns, fns...)
	return pkgb
}

// Scan applies the selector query and scans the result into the given value.
func (pkgb *PublicKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pkgb.build.ctx, ent.OpQueryGroupBy)
	if err := pkgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicKeyQuery, *PublicKeyGroupBy](ctx, pkgb.build, pkgb, pkgb.build.inters, v)
}

func (pkgb *PublicKeyGroupBy) sqlScan(ctx context.Context, root *PublicKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pkgb.fns))
	for _, fn := range pkgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pkgb.flds)+len(pkgb.fns))
		for _, f := range *pkgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pkgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pkgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PublicKeySelect is the builder for selecting fields of PublicKey entities.
type PublicKeySelect struct {
	*PublicKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pks *PublicKeySelect) Aggregate(fns ...AggregateFunc) *PublicKeySelect {
	pks.fns = append(pks.fns, fns...)
	return pks
}

// Scan applies the selector query and scans the result into the given value.
func (pks *PublicKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pks.ctx, ent.OpQuerySelect)
	if err := pks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicKeyQuery, *PublicKeySelect](ctx, pks.PublicKeyQuery, pks, pks.inters, v)
}

func (pks *PublicKeySelect) sqlScan(ctx context.Context, root *PublicKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pks.fns))
	for _, fn := range pks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
