// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hawa130/computility-cloud/ent/predicate"
	"github.com/hawa130/computility-cloud/ent/publickey"
)

// PublicKeyDelete is the builder for deleting a PublicKey entity.
type PublicKeyDelete struct {
	config
	hooks    []Hook
	mutation *PublicKeyMutation
}

// Where appends a list predicates to the PublicKeyDelete builder.
func (pkd *PublicKeyDelete) Where(ps ...predicate.PublicKey) *PublicKeyDelete {
	pkd.mutation.Where(ps...)
	return pkd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pkd *PublicKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pkd.sqlExec, pkd.mutation, pkd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pkd *PublicKeyDelete) ExecX(ctx context.Context) int {
	n, err := pkd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pkd *PublicKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(publickey.Table, sqlgraph.NewFieldSpec(publickey.FieldID, field.TypeString))
	if ps := pkd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pkd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pkd.mutation.done = true
	return affected, err
}

// PublicKeyDeleteOne is the builder for deleting a single PublicKey entity.
type PublicKeyDeleteOne struct {
	pkd *PublicKeyDelete
}

// Where appends a list predicates to the PublicKeyDelete builder.
func (pkdo *PublicKeyDeleteOne) Where(ps ...predicate.PublicKey) *PublicKeyDeleteOne {
	pkdo.pkd.mutation.Where(ps...)
	return pkdo
}

// Exec executes the deletion query.
func (pkdo *PublicKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := pkdo.pkd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{publickey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pkdo *PublicKeyDeleteOne) ExecX(ctx context.Context) {
	if err := pkdo.Exec(ctx); err != nil {
		panic(err)
	}
}
