[server]
address = ':8080'

[server.cors]
allowed_origins = ['*']
allowed_methods = ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE']
allowed_headers = []
exposed_headers = []
allow_credentials = false
max_age = 0

[database]
# 数据库驱动，可选 mysql, postgres
# 建议使用 MySQL/MariaDB（即 mysql）兼容性最好
driver = 'mysql'
url = '<user>:<pass>@tcp(localhost:3306)/<database>?parseTime=True'

[jwt]
private_key_path = 'ec-prime256v1-priv-key.pem'
# 有效期（小时）
duration = 24
# 距离有效期结束多少小时内自动续期
renew_duration = 12

[graphql]
endpoint = '/graphql'
playground_endpoint = '/playground'
introspection = false
playground = false

[argon2]
# 内存消耗（KB）默认为 64MB，即 64*1024=65536KB
memory = 65536
# 迭代次数，默认为 3
iterations = 3
parallelism = 2
salt_length = 16
key_length = 32
